Update patch set 1
Patch Set 1: I would prefer that you didn't submit this

I cannot cherrypick this change, even after multiple "repo sync". Always worked with previous kernel updates, so I'm a bit stumped about how to proceed.

From http://review.cyanogenmod.com/p/CyanogenMod/android_device_samsung_tuna
 * branch            refs/changes/31/14131/1 -> FETCH_HEAD
warning: Cannot merge binary files: kernel (HEAD vs. d0a8d69... Update kernel for 4.0.4)

error: could not apply d0a8d69... Update kernel for 4.0.4
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit -c d0a8d69'

Patch-set: 1